### ISSUE TITLE
PHP Memory Limit

### ISSUE THREAD

**Issue by pixelwatt** [joinville/docker-phpcs-wordpress#1]
Initial attempts to use for a test stage on a GitLab Runner resulted in a number of memory errors.

Example:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194312 bytes) in /usr/local/lib/php/PHP/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php on line 520`

A temp (or permanent?) fix was to add the following line under the code_lint job's script to increase PHP's memory limit:

```
code_lint:
  stage: test
  image: joinville/phpcs-wordpress
  script:
    - echo "memory_limit=-1" > /usr/local/etc/php/conf.d/memory-limit.ini
    - phpcs --standard=WordPress-Core --ignore=/inc/ --extensions=php .
```
